### ISSUE TITLE
Packets get buffered instead of dropped when a transceiver has send-only direction

### ISSUE THREAD

**Issue by KillingSpark** [webrtc-rs/webrtc#228]
### Problem

I experimented with setting transceivers to sendonly like this:

```rust
    for transceiver in peer_connection_offer.get_transceivers().await {
        transceiver.set_direction(RTCRtpTransceiverDirection::Sendonly).await;
    }
```

I do the necessary renegotiation, but (for simplicity) i have let the other side keep sending packets.

After a few seconds I re-enable the transceivers:

```rust
    for transceiver in peer_connection_offer.get_transceivers().await {
        transceiver.set_direction(RTCRtpTransceiverDirection::Sendrecv).await;
    }
```

Again, negotiation is happening.

I now get a bunch of packets in a short amount of time in a new track. Seems like a new track is created and it finds all the packets that have not been dropped and thinks they belong to it.

### What did I expect to happen
* The track does read packets that are sent by the other side while it is in Sendrecv direction
* The track doesn't read packets that are sent by the other side while it is in Sendrecv direction

### What happens
* A new track is created (this is fine i guess, after a renegotiation)
* The new track receives the packets of the time interval where it was set to Sendonly direction

### Related questions
* I don't think there is a way to check on a local track if the remote track has been set to no longer receive data right?
* Should I even be using the track to send packets after a renegotiation, and if no - what else a I supposed to do?

**Comment by algesten** [comment]
Doesn't seem to be much going on at the inbound.

https://github.com/webrtc-rs/srtp/blob/2512fc6bf56b043d85e765dbdd2808196b09d59a/src/session/mod.rs#L170-L178

srtp data arrives, it gets matched up to a `srtp::Stream` (funny name, because it's not encrypted). That stream has an internal `util::buffer`, which the data gets appended to for each packet.

For each new ssrc we end up in `PeerConnectionInternal::handle_incoming_ssrc`, which in turn calls the `on_track_handler`. I haven't exactly figured out why there is a new track created. However… those tracks are on the "reading side" of this `util::buffer`.

AFAIK, there isn't any mechanic that would stop the pushing of the data to `srtp::Stream::buffer`. The buffer eventually fills up, but unless something reads it, the data just sits there.

To fix this proper, it feels like the inbound should discard rather than retain when it knows no one is interested. It's probably three states: Unknown, Accept, Reject. At first, before we know whether the data is wanted, it would be Unknown, and we need to retain. Accept retains, Reject drops.

**Comment by KillingSpark** [comment]
I think it is reasonable (maybe even desriable) to create a new track after the second renegotiation. After all the original track might not have produced any data for a significant amount of time, so the code that reads from this track might just have give this up.

I think having these three states is a good idea. But I think after the negotiation has finished it is possible to tell for each stream if it should drop the packet or retain it, so there should not be a huge amount of packets retained in the unknown state.

**Comment by KillingSpark** [comment]
Did a fix to this make it into v0.5.0? The testcase I had that I noted down as "should be failing" is no longer doing that. Just wondering if I borked that test somehow without noticing or if there was a change to this on your side.

**Comment by k0nserv** [comment]
Was the initial bug for 0.4.0? In that case it possible that my changes have fixed this yes. 

One of the PRs listed under:


> Transceivers will now not stop when either or both directions are disabled. That is, applying and SDP with a=inactive will not stop the transceiver, instead attached senders and receivers will pause. A transceiver can be resurrected by setting direction back to e.g. a=sendrecv. The desired direction can be controlled with the newly introduced public method set_direction on RTCRtpTransceiver. 

in the [0.5.0 release notes](https://github.com/webrtc-rs/webrtc/blob/master/webrtc/CHANGELOG.md#050) is likely to have done it.

**Comment by KillingSpark** [comment]
Yes the initial bug was on a version before 0.5.0 (it was on a local copy that loosely followed master) so it's likely this issue is fixed :+1:

**Comment by k0nserv** [comment]
Cool, I'm closing this then.
