### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by chrisprobst** [webrtc-rs/webrtc#3]
Hi, first of all, I am a Pion lover. It's great to see movement in the Rust world. Since this project is very recent, how serious is this project? I am planning long-term for some of our software components. Rust might be valuable for us but we need WebRTC support. So don't get my question offensive in any way. Just curious if this is something I could base our stack on in the future.

Cheers
Chris

**Comment by rainliu** [comment]
Hi @chrisprobst,

Thanks for bringing up this issue. I am a Pion lover too and also a Rustacean. That's why I'd like to port Pion to Rust. Yes, I am taking this project seriously. But I can only work on this project on weekend days. Therefore, this project needs community's help to speed up the development. Contributors or pull requests are welcome.


Rain

**Comment by rainliu** [comment]
@Sean-Der,

Thanks for your mentioning this project in Slack #pion, and suggestions how to build a community for this project.

If you are willing, I can invite you as a member of this project.


Rain

**Comment by Sean-Der** [comment]
@rainliu I would love to join!

You are the leader/creator of the project. So tell me what I can do to help :) 

I would love to get a simple DataChannels example working. If we can make that happen I think you will get a huge amount of interest!

**Comment by metaclips** [comment]
@rainliu can we create issues splitting todos? I plan on contributing constantly and need to know tasks to be done.

**Comment by Sean-Der** [comment]
@rainliu I am happy to sketch out the APIs that it would take in ICE + PeerConnection to get a MVP going! I can create the issues. If you do that and then share you will get even more people.

With Pion the most difficult thing was changing bad public APIs. So would love to share that knowledge. Things like Trickle ICE, Media APIs and re-negotiation were really painful :)

**Comment by rainliu** [comment]
@Sean-Der, sure, please go ahead to create the issues. Thanks.

**Comment by breebee** [comment]
If webrtc has all these obstacles due to networking NAT traversals and firewalls or whatever, could there be a way to implement something like GNU GNS in a webassembly WASM/WASI module served over https to resolve and make the peer connections directly from the resolver? 

**PS, I actually passed by pion just because it wasnt Rust :) I am actually really excited about this port!

**Comment by breebee** [comment]
For example instead of using a signaling mechanism, use the hash table which the server acts as a public peer point of access. Too far out?

**Comment by falconmick** [comment]
@Sean-Der damn lol your everywhere I look

**Comment by Sparika** [comment]
Hi everyone. I'm looking into using WebRTC-rs, a MVP PeerConnection would be enough to start. Is there any progress on the roadmap/API/list of issues? I need to decide between that or pion. ;)

**Comment by rainliu** [comment]
PeerConnection is not ready yet. We are still working on TURN/ICE.

You can alway use Pion for your proof of concept.

**Comment by trivigy** [comment]
@rainliu this is awesome. I would love to help out in some ways with writing code. I wrote a bunch of the pion's go code. The whole SDP state based parsing was my rewrite. Since I have migrated quiet fully into rust I should be able to help pretty much anywhere in the stack. Will start looking through the code until I find some place I can contribute. Is there a rust specific community chat going somewhere? Like gopher's pion but rust specific.

**Comment by rainliu** [comment]
@trivigy, thank you for offering the help. Please look around the code base to find any place you would like to contribute. Webrtc-rs needs more contributions from the community so we can speed up the developement.

**Comment by trivigy** [comment]
> Is there a rust specific community chat going somewhere?

@rainliu If not, you care if I set up one?

**Comment by rainliu** [comment]
@trivigy, please go ahead to set up. Thank you.

**Comment by trivigy** [comment]
For posterity leaving this here https://discord.gg/4Ju8UHdXMs. I make a few PRs on this repo, `ice`, and `sdp` since those are the first ones I am giving a read first. But I'll keep updating things as I go.
