### ISSUE TITLE
why not use cargo workspace instead of git submodule?

### ISSUE THREAD

**Issue by koushiro** [webrtc-rs/webrtc#73]

**Comment by rainliu** [comment]
under [webrtc/crates](https://github.com/webrtc-rs/webrtc/blob/master/crates/Cargo.toml), we do use cargo workspace with the usage of git submodule.

I believe this combines both advantages of cargo workspace and git submodule. It means
1). use separate git repo for each crate, so that it can be also used outside of webrtc-rs project too.
2). cargo workspace under webrtc/crates with git submodule can help the Monorepo Setup and keep each crate version up to date and consistent.
