### ISSUE TITLE
[WebRTC] join interop tests in https://github.com/sipsorcery/webrtc-echoes

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/webrtc#93]
Interoperability Tests with other webrtc implementation in
https://github.com/sipsorcery/webrtc-echoes

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue. Can you guide me further on what needs to be done?🙂

**Comment by rainliu** [comment]
Please follows the spec docs in https://github.com/sipsorcery/webrtc-echoes/tree/master/doc

**Comment by himanshu007-creator** [comment]
in simple terms, what I think it means is, I have to merge the three markdown files right?!

**Comment by rainliu** [comment]
you need to follow the test spec to write client and server app based on webrtc-rs's API, and submit PR to webrtc-echoes repo.

**Comment by rainliu** [comment]
Just submit a PR https://github.com/sipsorcery/webrtc-echoes/pull/41 to webrtc-echoes

**Comment by rainliu** [comment]
two issues:

1. interop-tests (kurento, webrtc-rs)
https://github.com/sipsorcery/webrtc-echoes/runs/3714395738?check_suite_focus=true

2. interop-tests (webrtc-rs, aiortc)
https://github.com/sipsorcery/webrtc-echoes/runs/3714395809?check_suite_focus=true

**Comment by shinyoshiaki** [comment]
Hi! I'm the author of werift.
The DTLS negotiation problem between webrtc-rs and werift was caused by the fact that the size of the SerialNumber in the x509 certificate generated by werift was larger than 20 octets in some cases. The cryptographic library of rust seems to validate the size of SerialNumber strictly.
I've fixed the SerialNumber size in werift, which should fix this problem.
